# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c5c9ac776805886d60a2a86c2a35fc22fc8cf35603c78a01354bfdb6e1f50b2c57518bc18573c6f6ea96bddd974beff3768cb08cb11dbf33c8fd761573ecd4

test:
  secret_key_base: 47e8a0fb9a07b0f82c44160caa37af7621585e0956476e441afd405c696441aa13bd12d0d6f26c02267d3c54ec585914b9dab9e1f5be84badc053302483a8f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
